// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: task-api/services.proto

package task

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TaskServiceClient is the client API for TaskService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TaskServiceClient interface {
	CreateTask(ctx context.Context, in *CreateTaskRequest, opts ...grpc.CallOption) (*TaskEntity, error)
	GetTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*TaskEntity, error)
	ListTask(ctx context.Context, in *ListTaskRequest, opts ...grpc.CallOption) (*TaskCollection, error)
	DeleteTask(ctx context.Context, in *DeleteTaskRequest, opts ...grpc.CallOption) (*DeleteTaskResponse, error)
	UpdateTask(ctx context.Context, in *UpdateTaskRequest, opts ...grpc.CallOption) (*TaskEntity, error)
	CompleteTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*TaskEntity, error)
}

type taskServiceClient struct {
	cc *grpc.ClientConn
}

func NewTaskServiceClient(cc *grpc.ClientConn) TaskServiceClient {
	return &taskServiceClient{cc}
}

func (c *taskServiceClient) CreateTask(ctx context.Context, in *CreateTaskRequest, opts ...grpc.CallOption) (*TaskEntity, error) {
	out := new(TaskEntity)
	err := c.cc.Invoke(ctx, "/task.v1.TaskService/CreateTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) GetTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*TaskEntity, error) {
	out := new(TaskEntity)
	err := c.cc.Invoke(ctx, "/task.v1.TaskService/GetTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) ListTask(ctx context.Context, in *ListTaskRequest, opts ...grpc.CallOption) (*TaskCollection, error) {
	out := new(TaskCollection)
	err := c.cc.Invoke(ctx, "/task.v1.TaskService/ListTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) DeleteTask(ctx context.Context, in *DeleteTaskRequest, opts ...grpc.CallOption) (*DeleteTaskResponse, error) {
	out := new(DeleteTaskResponse)
	err := c.cc.Invoke(ctx, "/task.v1.TaskService/DeleteTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) UpdateTask(ctx context.Context, in *UpdateTaskRequest, opts ...grpc.CallOption) (*TaskEntity, error) {
	out := new(TaskEntity)
	err := c.cc.Invoke(ctx, "/task.v1.TaskService/UpdateTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) CompleteTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*TaskEntity, error) {
	out := new(TaskEntity)
	err := c.cc.Invoke(ctx, "/task.v1.TaskService/CompleteTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TaskServiceServer is the server API for TaskService service.
type TaskServiceServer interface {
	CreateTask(context.Context, *CreateTaskRequest) (*TaskEntity, error)
	GetTask(context.Context, *GetTaskRequest) (*TaskEntity, error)
	ListTask(context.Context, *ListTaskRequest) (*TaskCollection, error)
	DeleteTask(context.Context, *DeleteTaskRequest) (*DeleteTaskResponse, error)
	UpdateTask(context.Context, *UpdateTaskRequest) (*TaskEntity, error)
	CompleteTask(context.Context, *GetTaskRequest) (*TaskEntity, error)
}

func RegisterTaskServiceServer(s *grpc.Server, srv TaskServiceServer) {
	s.RegisterService(&_TaskService_serviceDesc, srv)
}

func _TaskService_CreateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).CreateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/task.v1.TaskService/CreateTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).CreateTask(ctx, req.(*CreateTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_GetTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).GetTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/task.v1.TaskService/GetTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).GetTask(ctx, req.(*GetTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_ListTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).ListTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/task.v1.TaskService/ListTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).ListTask(ctx, req.(*ListTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_DeleteTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).DeleteTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/task.v1.TaskService/DeleteTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).DeleteTask(ctx, req.(*DeleteTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_UpdateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).UpdateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/task.v1.TaskService/UpdateTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).UpdateTask(ctx, req.(*UpdateTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_CompleteTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).CompleteTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/task.v1.TaskService/CompleteTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).CompleteTask(ctx, req.(*GetTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TaskService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "task.v1.TaskService",
	HandlerType: (*TaskServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTask",
			Handler:    _TaskService_CreateTask_Handler,
		},
		{
			MethodName: "GetTask",
			Handler:    _TaskService_GetTask_Handler,
		},
		{
			MethodName: "ListTask",
			Handler:    _TaskService_ListTask_Handler,
		},
		{
			MethodName: "DeleteTask",
			Handler:    _TaskService_DeleteTask_Handler,
		},
		{
			MethodName: "UpdateTask",
			Handler:    _TaskService_UpdateTask_Handler,
		},
		{
			MethodName: "CompleteTask",
			Handler:    _TaskService_CompleteTask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "task-api/services.proto",
}

func init() { proto.RegisterFile("task-api/services.proto", fileDescriptor_services_63b31692be3d3410) }

var fileDescriptor_services_63b31692be3d3410 = []byte{
	// 325 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0xd2, 0xc1, 0x4a, 0xf3, 0x40,
	0x10, 0x07, 0x70, 0xfa, 0x11, 0xda, 0xb2, 0xfd, 0xec, 0x61, 0x53, 0x8c, 0xc6, 0x92, 0x43, 0x8e,
	0x82, 0x09, 0xea, 0xcd, 0xa3, 0x51, 0xbc, 0xd4, 0x8b, 0x55, 0x90, 0xdc, 0xd6, 0x74, 0x08, 0x4b,
	0x93, 0x6c, 0xcc, 0xae, 0x05, 0x11, 0x2f, 0xbe, 0x81, 0xf8, 0x52, 0x1e, 0x05, 0x5f, 0x40, 0x82,
	0x0f, 0x22, 0xbb, 0xd9, 0x24, 0x2d, 0x95, 0x82, 0xd7, 0xff, 0xcc, 0xfc, 0x98, 0x1d, 0x16, 0x59,
	0x82, 0xf0, 0xf9, 0x01, 0xc9, 0xa9, 0xcf, 0xa1, 0x58, 0xd0, 0x08, 0xb8, 0x97, 0x17, 0x4c, 0x30,
	0xdc, 0x93, 0x05, 0x6f, 0x71, 0x68, 0x8f, 0x63, 0xc6, 0xe2, 0x04, 0x7c, 0xd9, 0x43, 0xb2, 0x8c,
	0x09, 0x22, 0x28, 0xcb, 0x74, 0x9b, 0xdd, 0xce, 0xa7, 0xc0, 0x39, 0x89, 0xeb, 0xf9, 0xa3, 0x57,
	0x03, 0x0d, 0xae, 0x09, 0x9f, 0x4f, 0x2b, 0x16, 0x4f, 0x11, 0x0a, 0x0a, 0x20, 0x02, 0x64, 0x88,
	0x6d, 0x4f, 0xf3, 0x5e, 0x1b, 0x5e, 0xc1, 0xfd, 0x03, 0x70, 0x61, 0x9b, 0x4d, 0x4d, 0xa6, 0xe7,
	0x99, 0xa0, 0xe2, 0xd1, 0x1d, 0xbd, 0x7c, 0x7e, 0xbf, 0xfd, 0x1b, 0xba, 0x5d, 0x5f, 0x16, 0xf9,
	0x89, 0x41, 0x05, 0xa4, 0x78, 0x82, 0x7a, 0x17, 0x20, 0x94, 0x68, 0x35, 0x53, 0x3a, 0xd9, 0xc8,
	0x99, 0x8a, 0xdb, 0xc2, 0x83, 0x8a, 0xf3, 0x9f, 0xe8, 0xec, 0x19, 0x5f, 0xa2, 0xfe, 0x84, 0xf2,
	0x8a, 0xdb, 0x69, 0xa6, 0xea, 0xa8, 0xf6, 0xac, 0x15, 0x2f, 0x60, 0x49, 0x02, 0x91, 0xbc, 0x88,
	0x3b, 0x54, 0x66, 0x1f, 0xeb, 0x15, 0x71, 0x88, 0xd0, 0x19, 0x24, 0xb0, 0xf6, 0xe2, 0x36, 0xac,
	0xc9, 0xbd, 0x5f, 0x6b, 0x3c, 0x67, 0x19, 0x87, 0x7a, 0xd5, 0xfd, 0x95, 0x55, 0x6f, 0x11, 0xba,
	0xc9, 0x67, 0xeb, 0xd7, 0x6c, 0xc3, 0x8d, 0xcf, 0xdf, 0x55, 0xa6, 0x69, 0x2f, 0x9b, 0xfa, 0xa4,
	0x21, 0xfa, 0x1f, 0xb0, 0x34, 0x6f, 0xf6, 0xfe, 0xdb, 0x5d, 0xc7, 0x0a, 0xde, 0x76, 0x47, 0xcb,
	0x70, 0xa4, 0xbd, 0x53, 0xfc, 0x5e, 0x3a, 0x9d, 0x8f, 0xd2, 0xe9, 0x7c, 0x95, 0x4e, 0x27, 0x34,
	0x64, 0xcb, 0x5d, 0x57, 0x7d, 0x97, 0xe3, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xfc, 0xf0, 0xec,
	0x46, 0x89, 0x02, 0x00, 0x00,
}
